### ISSUE TITLE
Remove node

### ISSUE THREAD

**Issue by tudorpintea999** [broxus/stever-node-tools#1]
Not an issue, tried to approach the team on discord but not a chance. I m creating a bash script that fully automates the process of installation and starting the node and to test it I want to completely remove the node from the server. How to do this ? thanks

**Comment by Rexagon** [comment]
`nodekeeper` was written precisely for this purpose. It is either used interactively (when setting up a single node - there are just a couple of steps that would be needed for using your script anyway), or via smth like Ansible (nodekeeper supports "template" init mode).

There is probably no need for such a script. Besides, another third-party component is a place for attacks.

**Comment by Rexagon** [comment]
But if I understood your question correctly, then it is enough to stop systemd services and uninstall `nodekeeper` (if installed as .deb package) or delete `~/.nodekeeper` folder (if installed via cargo)

**Comment by tudorpintea999** [comment]
thanks for the answer. The idea is to make a one-line run command for people want to run a testnet node just for fun/learning/airdrop
